#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd

  cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
_SUB_ROOT="$(abs_dirname "$libexec_path")"
export _SUB_ROOT
export PATH="${libexec_path}:$PATH"

command="$1"

if [[ "$command" =~ [a-z]:[a-z] ]]; then
    command="$(echo "$command" | cut -d: -f2)-$(echo "$command" | cut -d: -f1)"
fi

case "$command" in
"" | "-h" | "--help" )
  exec sub-help
  ;;
* )
  command_path="$(command -v "sub-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "sub: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
